# Generated by Django 4.2.1 on 2023-05-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('DataN', models.DateField(max_length=20)),
                ('nome', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=35)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
