# Generated by Django 4.2.1 on 2023-05-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LavaJatoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='foto',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
