# Generated by Django 4.2.1 on 2023-05-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LavaJatoapp', '0004_alter_dados_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='foto',
            field=models.ImageField(upload_to='LavaJatoapp/static/img'),
        ),
    ]
