# Generated by Django 4.1.7 on 2023-05-18 14:02

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LavaJatoapp', '0007_alter_dados_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='foto',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/static/img'), upload_to=''),
        ),
    ]
